[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
(
  /(
      venv         # exclude a few common directories in the
    | src/bronfood
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''