# Generated by Django 4.2.7 on 2024-02-18 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', regex='^\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')])),
                ('cardholder_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+\\s[a-zA-Z]+$')])),
                ('expiration_date', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^\\d{2}/\\d{2}$')])),
                ('cvv', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^\\d{3}$')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card', to='client.client')),
            ],
        ),
    ]
