# Generated by Django 4.2.7 on 2023-12-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requisites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequisites',
            name='card_number',
            field=models.CharField(max_length=16),
            preserve_default=False,
        ),
    ]
