# Generated by Django 4.2.7 on 2023-12-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('payment_requisites', '0002_paymentrequisites_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequisites',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card', to='client.client'),
        ),
    ]
