# Generated by Django 4.2.7 on 2023-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requisites', '0003_alter_paymentrequisites_client'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentrequisites',
            constraint=models.UniqueConstraint(fields=('card_number', 'cvv', 'cardholder_name'), name='unique_card_number_cvv_cardholder_name'),
        ),
    ]
