# Generated by Django 4.2.7 on 2024-01-30 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requisites', '0004_paymentrequisites_unique_card_number_cvv_cardholder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequisites',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentrequisites',
            name='expiration_data',
        ),
        migrations.AddField(
            model_name='paymentrequisites',
            name='expiration_date',
            field=models.CharField(default='10/25', max_length=255, validators=[django.core.validators.RegexValidator(regex='^\\d{2}/\\d{2}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequisites',
            name='card_number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(regex='^\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='paymentrequisites',
            name='cardholder_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+\\s[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='paymentrequisites',
            name='cvv',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^\\d{3}$')]),
        ),
    ]
