# Generated by Django 4.2.7 on 2024-02-04 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requisites', '0005_remove_paymentrequisites_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequisites',
            name='card_number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid registration number in the format ABC123.', regex='^\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')]),
        ),
    ]
