# Generated by Django 4.2.7 on 2024-02-04 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requisites', '0006_alter_paymentrequisites_card_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentrequisites',
            name='unique_card_number_cvv_cardholder_name',
        ),
        migrations.AlterField(
            model_name='paymentrequisites',
            name='card_number',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_number', message='', regex='^\\d{4}\\s\\d{4}\\s\\d{4}\\s\\d{4}$')]),
        ),
    ]
