# Generated by Django 4.2.7 on 2023-11-26 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneSmsOtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Значение должно быть больше 0.'), django.core.validators.MaxValueValidator(9999, message='Значение должно быть меньше 10000')], verbose_name='Одноразовый пароль')),
                ('issue_status', models.IntegerField(choices=[(1, 'Registration'), (2, 'Password Recovery'), (3, 'Editing'), (4, 'Payment Confirmation')], verbose_name='Статус выдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
