# Generated by Django 4.2.10 on 2024-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesmsotpverification',
            name='attempt_counter',
            field=models.IntegerField(default=0, verbose_name='Attempt counter'),
        ),
        migrations.AlterField(
            model_name='phonesmsotpverification',
            name='message',
            field=models.CharField(choices=[('Your code for registration in the Broonfood: ', 'Registration'), ('Your password recovery code in the Broonfood: ', 'Password Recovery'), ('Your code for editing data in the Broonfood: ', 'Editing'), ('Your payment confirmation code for the Broonfood: ', 'Payment Confirmation')], max_length=255, verbose_name='Sms message'),
        ),
    ]
