# Generated by Django 4.2.7 on 2023-12-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phonesmsotpverification',
            table='phone_sms_otp_verification',
        ),
    ]
