# Generated by Django 4.2.10 on 2024-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_phonesmsotpverification_attempt_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonesmsotpverification',
            name='message',
            field=models.CharField(choices=[('Your code for registration in the Broonfood: ', 'Registration'), ('Your password recovery code in the Broonfood: ', 'Password Recovery'), ('Your code for editing data in the Broonfood: ', 'Editing'), ('Your payment confirmation code for the Broonfood: ', 'Payment Confirmation')], max_length=255, verbose_name='Sms message'),
        ),
    ]
