# Generated by Django 4.2.10 on 2024-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_admin', '0002_alter_restaurantadmin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantadmin',
            name='login',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantadmin',
            name='password',
            field=models.CharField(default=2, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
