# Generated by Django 4.2.10 on 2024-06-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_order_preparationstatus'),
        ('restaurant_admin', '0004_remove_restaurantadmin_restaurant_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantadmin',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
