# Generated by Django 4.2.7 on 2023-12-05 08:29

import bronfood.core.useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('STAFF', 'staff'), ('CLIENT', 'client'), ('OWNER', 'owner'), ('RESTAURANT_ADMIN', 'restaurant_admin')], default='CLIENT', max_length=16)),
                ('username', models.CharField(max_length=200, validators=[bronfood.core.useraccount.validators.CustomUnicodeUsernameValidator])),
                ('phone', models.CharField(max_length=18, unique=True)),
                ('active_status', models.SmallIntegerField(choices=[(1, 'Unconfirmed'), (2, 'Confirmed'), (3, 'Blocked')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
