# Generated by Django 4.2.7 on 2023-12-17 08:02

import bronfood.core.useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('CLIENT', 'client'), ('OWNER', 'owner'), ('RESTAURANT_ADMIN', 'restaurant_admin')], default='CLIENT', max_length=16)),
                ('username', models.CharField(max_length=200, validators=[bronfood.core.useraccount.validators.CustomUnicodeUsernameValidator])),
                ('phone', models.CharField(max_length=18, unique=True, validators=[bronfood.core.useraccount.validators.OnlyDigitsValidator])),
                ('status', models.SmallIntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed'), (2, 'Blocked')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
