# Generated by Django 4.2.7 on 2023-12-24 16:59

import bronfood.core.useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fullname',
            field=models.CharField(max_length=40, validators=[bronfood.core.useraccount.validators.UsernameValidator]),
        ),
    ]
