# Generated by Django 4.2.7 on 2024-01-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounttempdata',
            old_name='data_code',
            new_name='temp_data_code',
        ),
    ]
