# Generated by Django 4.2.7 on 2024-01-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_tempuseraccountdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuseraccountdata',
            name='new_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
