# Generated by Django 4.2.7 on 2023-12-29 08:43

import bronfood.core.useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_useraccount_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fullname',
            field=models.CharField(max_length=40, validators=[bronfood.core.useraccount.validators.FullnameValidator]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
