# Generated by Django 4.2.7 on 2024-01-23 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_alter_useraccounttempdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounttempdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_temp_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
