# Generated by Django 4.2.7 on 2024-01-25 20:25

import bronfood.core.useraccount.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_useraccounttempdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounttempdata',
            name='new_fullname',
            field=models.CharField(max_length=40, null=True, validators=[bronfood.core.useraccount.validators.FullnameValidator]),
        ),
        migrations.AddField(
            model_name='useraccounttempdata',
            name='new_phone',
            field=models.CharField(max_length=18, null=True, validators=[bronfood.core.useraccount.validators.KazakhstanPhoneNumberValidator]),
        ),
    ]
