# Generated by Django 4.2.10 on 2024-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favorites',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='shop',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Рейтинг'),
        ),
    ]
