# Generated by Django 4.2.10 on 2024-07-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Идентификатор"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название варианта"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="menu",
            name="category",
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.OneToOneField(
                default=1111,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurants.restaurant",
            ),
            preserve_default=False,
        ),
    ]
