# Generated by Django 4.2.10 on 2024-07-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("restaurants", "0002_featurechoice_remove_menu_category_menu_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                default=223123123,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
            ),
            preserve_default=False,
        ),
    ]
