# Generated by Django 4.2.10 on 2024-06-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('restaurants', '0003_remove_favorites_unique_shop_order_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='Понравился ли ресторан')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Ресторан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Пользовательский ресторан',
                'verbose_name_plural': 'Пользовательские рестораны',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
