# Generated by Django 4.2.10 on 2024-06-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_favorites_unique_shop_order_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmeal',
            name='itemDescription',
        ),
        migrations.RemoveField(
            model_name='orderedmeal',
            name='itemPrice',
        ),
        migrations.AddField(
            model_name='orderedmeal',
            name='orderedMeal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.meal', verbose_name='Заказанное блюдо'),
        ),
        migrations.AlterField(
            model_name='orderedmeal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderedmeal',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество блюд'),
        ),
    ]
