# Generated by Django 4.2.10 on 2024-06-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_favorites_unique_shop_order_admin_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealinbasket',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество блюд'),
        ),
    ]
