# Generated by Django 4.2.7 on 2024-06-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_rating'),
        ('restaurants', '0003_remove_favorites_unique_shop_order_admin_confirmed_and_more'),
    ]

    operations = [
    ]
