# Generated by Django 4.2.10 on 2024-06-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_orderedmeal_itemdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clientId',
            new_name='userId',
        ),
    ]
