# Generated by Django 4.2.7 on 2024-06-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_merge_20240619_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealinbasket',
            name='basket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mealinbasket', to='restaurants.basket', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='meals',
            field=models.ManyToManyField(related_name='baskets', through='restaurants.MealInBasket', to='restaurants.meal', verbose_name='Блюда в корзине'),
        ),
        migrations.AlterField(
            model_name='mealinbasket',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество блюд'),
        ),
    ]
