# Generated by Django 4.2.10 on 2024-06-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_rename_clientid_order_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmationStatus',
        ),
    ]
