# Generated by Django 4.2.10 on 2024-06-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_remove_order_confirmationstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reviewStatus',
        ),
    ]
