# Generated by Django 4.2.10 on 2024-06-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_order_reviewstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('notPaid', 'Не оплачено')], default='notPaid', max_length=7, verbose_name='Статус оплаты'),
        ),
    ]
