# Generated by Django 4.2.10 on 2024-06-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_order_restaurantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurantId',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Ресторан'),
            preserve_default=False,
        ),
    ]
