# Generated by Django 4.2.10 on 2024-06-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_order_restaurantid_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurantId',
        ),
    ]
