# Generated by Django 4.2.10 on 2024-06-17 10:33

import bronfood.core.restaurants.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_rename_restaurant_order_restaurantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=bronfood.core.restaurants.utils.create_order, max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
