# Generated by Django 4.2.10 on 2024-06-27 03:36

import bronfood.core.restaurants.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('restaurants', '0011_rename_restaurant_order_restaurantid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparationStatus',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('confirmed', 'Подтверждено'), ('notConfirmed', 'Не подтверждено')], default='waiting', max_length=13, verbose_name='Статус подготовки заказа'),
        ),
        migrations.AlterField(
            model_name='mealinbasket',
            name='count',
            field=models.BigIntegerField(default=0, verbose_name='Количество блюд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=bronfood.core.restaurants.utils.create_order, max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.CreateModel(
            name='UserLikedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='Понравился ли ресторан')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Ресторан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Пользовательский ресторан',
                'verbose_name_plural': 'Пользовательские рестораны',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
