# Generated by Django 4.2.10 on 2024-06-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_order_preparationstatus_alter_mealinbasket_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='isLiked',
            field=models.BooleanField(default=False, verbose_name='Понравился ли ресторан'),
        ),
    ]
