# Generated by Django 4.2.10 on 2024-06-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparationStatus',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('confirmed', 'Подтверждено'), ('notConfirmed', 'Не подтверждено')], default='waiting', max_length=13, verbose_name='Статус подготовки заказа'),
        ),
    ]
