name: Code check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install black
      - name: run flake8
        run: flake8
      - name: run black
        run: black --diff -S .

          