name: CI

on:
  push:
    branches:
      [ develop_backup, feature/deploy ]

  pull_request:
    branches:
      [ develop_backup, feature/deploy ]

jobs:

  test:
  # актуальная версия убунту сервера
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
        # актуальная версия питона
          python-version: '3.10'

      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install black
          pip install -r requirements.txt

      - name: run flake8
        run: flake8

      - name: run black
        run: black --diff -S .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Start PostgreSQL with docker-compose
        run: docker-compose -f infra/docker-compose.only_db.yml up -d

      - name: Set migrations
        run: |
          python src/manage.py makemigrations
          python src/manage.py makemigrations phone
          python src/manage.py migrate

      - name: Stop PostgreSQL with docker-compose
        run: docker-compose down
